/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthorIndexRouteImport } from './routes/author.index'
import { Route as AuthorAchievementsRouteImport } from './routes/author.achievements'
import { Route as AuthorCreateRouteImport } from './routes/author.create'
import { Route as AuthorLoginRouteImport } from './routes/author.login'
import { Route as AuthorParticipatedRouteImport } from './routes/author.participated'
import { Route as AuthorQuestionsRouteImport } from './routes/author.questions'
import { Route as AuthorRegisterRouteImport } from './routes/author.register'
import { Route as AuthorSessionsRouteImport } from './routes/author.sessions'
import { Route as AuthorTemplatesRouteImport } from './routes/author.templates'
import { Route as AuthorToolsRouteImport } from './routes/author.tools'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesConnectDotsRouteImport } from './routes/games.connect-dots'
import { Route as GamesJigsawRouteImport } from './routes/games.jigsaw'
import { Route as GamesQuizRouteImport } from './routes/games.quiz'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinLobbyRouteImport } from './routes/join.lobby'
import { Route as JoinNameRouteImport } from './routes/join.name'
import { Route as PlayRoomIdRouteImport } from './routes/play.$roomId'
import { Route as ShareShareSlugRouteImport } from './routes/share.$shareSlug'
import { Route as AuthorRoomRoomIdRouteImport } from './routes/author.room.$roomId'
import { Route as AuthorSessionsRoomIdRouteImport } from './routes/author.sessions.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorAchievementsRoute = AuthorAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorCreateRoute = AuthorCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorLoginRoute = AuthorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorParticipatedRoute = AuthorParticipatedRouteImport.update({
  id: '/participated',
  path: '/participated',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorQuestionsRoute = AuthorQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorRegisterRoute = AuthorRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorSessionsRoute = AuthorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorTemplatesRoute = AuthorTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorToolsRoute = AuthorToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthorRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesConnectDotsRoute = GamesConnectDotsRouteImport.update({
  id: '/games/connect-dots',
  path: '/games/connect-dots',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJigsawRoute = GamesJigsawRouteImport.update({
  id: '/games/jigsaw',
  path: '/games/jigsaw',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuizRoute = GamesQuizRouteImport.update({
  id: '/games/quiz',
  path: '/games/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinRoute,
} as any)
const JoinLobbyRoute = JoinLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => JoinRoute,
} as any)
const JoinNameRoute = JoinNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => JoinRoute,
} as any)
const PlayRoomIdRoute = PlayRoomIdRouteImport.update({
  id: '/play/$roomId',
  path: '/play/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareSlugRoute = ShareShareSlugRouteImport.update({
  id: '/share/$shareSlug',
  path: '/share/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoomRoomIdRoute = AuthorRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorSessionsRoomIdRoute = AuthorSessionsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AuthorSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/author': typeof AuthorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/author/achievements': typeof AuthorAchievementsRoute
  '/author/create': typeof AuthorCreateRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/participated': typeof AuthorParticipatedRoute
  '/author/questions': typeof AuthorQuestionsRoute
  '/author/register': typeof AuthorRegisterRoute
  '/author/sessions': typeof AuthorSessionsRouteWithChildren
  '/author/templates': typeof AuthorTemplatesRoute
  '/author/tools': typeof AuthorToolsRoute
  '/games/connect-dots': typeof GamesConnectDotsRoute
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/quiz': typeof GamesQuizRoute
  '/join/lobby': typeof JoinLobbyRoute
  '/join/name': typeof JoinNameRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/share/$shareSlug': typeof ShareShareSlugRoute
  '/author/': typeof AuthorIndexRoute
  '/games/': typeof GamesIndexRoute
  '/join/': typeof JoinIndexRoute
  '/author/room/$roomId': typeof AuthorRoomRoomIdRoute
  '/author/sessions/$roomId': typeof AuthorSessionsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/author/achievements': typeof AuthorAchievementsRoute
  '/author/create': typeof AuthorCreateRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/participated': typeof AuthorParticipatedRoute
  '/author/questions': typeof AuthorQuestionsRoute
  '/author/register': typeof AuthorRegisterRoute
  '/author/sessions': typeof AuthorSessionsRouteWithChildren
  '/author/templates': typeof AuthorTemplatesRoute
  '/author/tools': typeof AuthorToolsRoute
  '/games/connect-dots': typeof GamesConnectDotsRoute
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/quiz': typeof GamesQuizRoute
  '/join/lobby': typeof JoinLobbyRoute
  '/join/name': typeof JoinNameRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/share/$shareSlug': typeof ShareShareSlugRoute
  '/author': typeof AuthorIndexRoute
  '/games': typeof GamesIndexRoute
  '/join': typeof JoinIndexRoute
  '/author/room/$roomId': typeof AuthorRoomRoomIdRoute
  '/author/sessions/$roomId': typeof AuthorSessionsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/author': typeof AuthorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/author/achievements': typeof AuthorAchievementsRoute
  '/author/create': typeof AuthorCreateRoute
  '/author/login': typeof AuthorLoginRoute
  '/author/participated': typeof AuthorParticipatedRoute
  '/author/questions': typeof AuthorQuestionsRoute
  '/author/register': typeof AuthorRegisterRoute
  '/author/sessions': typeof AuthorSessionsRouteWithChildren
  '/author/templates': typeof AuthorTemplatesRoute
  '/author/tools': typeof AuthorToolsRoute
  '/games/connect-dots': typeof GamesConnectDotsRoute
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/quiz': typeof GamesQuizRoute
  '/join/lobby': typeof JoinLobbyRoute
  '/join/name': typeof JoinNameRoute
  '/play/$roomId': typeof PlayRoomIdRoute
  '/share/$shareSlug': typeof ShareShareSlugRoute
  '/author/': typeof AuthorIndexRoute
  '/games/': typeof GamesIndexRoute
  '/join/': typeof JoinIndexRoute
  '/author/room/$roomId': typeof AuthorRoomRoomIdRoute
  '/author/sessions/$roomId': typeof AuthorSessionsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/author'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/author/achievements'
    | '/author/create'
    | '/author/login'
    | '/author/participated'
    | '/author/questions'
    | '/author/register'
    | '/author/sessions'
    | '/author/templates'
    | '/author/tools'
    | '/games/connect-dots'
    | '/games/jigsaw'
    | '/games/quiz'
    | '/join/lobby'
    | '/join/name'
    | '/play/$roomId'
    | '/share/$shareSlug'
    | '/author/'
    | '/games/'
    | '/join/'
    | '/author/room/$roomId'
    | '/author/sessions/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/author/achievements'
    | '/author/create'
    | '/author/login'
    | '/author/participated'
    | '/author/questions'
    | '/author/register'
    | '/author/sessions'
    | '/author/templates'
    | '/author/tools'
    | '/games/connect-dots'
    | '/games/jigsaw'
    | '/games/quiz'
    | '/join/lobby'
    | '/join/name'
    | '/play/$roomId'
    | '/share/$shareSlug'
    | '/author'
    | '/games'
    | '/join'
    | '/author/room/$roomId'
    | '/author/sessions/$roomId'
  id:
    | '__root__'
    | '/'
    | '/author'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/author/achievements'
    | '/author/create'
    | '/author/login'
    | '/author/participated'
    | '/author/questions'
    | '/author/register'
    | '/author/sessions'
    | '/author/templates'
    | '/author/tools'
    | '/games/connect-dots'
    | '/games/jigsaw'
    | '/games/quiz'
    | '/join/lobby'
    | '/join/name'
    | '/play/$roomId'
    | '/share/$shareSlug'
    | '/author/'
    | '/games/'
    | '/join/'
    | '/author/room/$roomId'
    | '/author/sessions/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorRoute: typeof AuthorRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  GamesConnectDotsRoute: typeof GamesConnectDotsRoute
  GamesJigsawRoute: typeof GamesJigsawRoute
  GamesQuizRoute: typeof GamesQuizRoute
  PlayRoomIdRoute: typeof PlayRoomIdRoute
  ShareShareSlugRoute: typeof ShareShareSlugRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/achievements': {
      id: '/author/achievements'
      path: '/achievements'
      fullPath: '/author/achievements'
      preLoaderRoute: typeof AuthorAchievementsRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/create': {
      id: '/author/create'
      path: '/create'
      fullPath: '/author/create'
      preLoaderRoute: typeof AuthorCreateRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/login': {
      id: '/author/login'
      path: '/login'
      fullPath: '/author/login'
      preLoaderRoute: typeof AuthorLoginRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/participated': {
      id: '/author/participated'
      path: '/participated'
      fullPath: '/author/participated'
      preLoaderRoute: typeof AuthorParticipatedRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/questions': {
      id: '/author/questions'
      path: '/questions'
      fullPath: '/author/questions'
      preLoaderRoute: typeof AuthorQuestionsRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/register': {
      id: '/author/register'
      path: '/register'
      fullPath: '/author/register'
      preLoaderRoute: typeof AuthorRegisterRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/sessions': {
      id: '/author/sessions'
      path: '/sessions'
      fullPath: '/author/sessions'
      preLoaderRoute: typeof AuthorSessionsRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/templates': {
      id: '/author/templates'
      path: '/templates'
      fullPath: '/author/templates'
      preLoaderRoute: typeof AuthorTemplatesRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/tools': {
      id: '/author/tools'
      path: '/tools'
      fullPath: '/author/tools'
      preLoaderRoute: typeof AuthorToolsRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/connect-dots': {
      id: '/games/connect-dots'
      path: '/games/connect-dots'
      fullPath: '/games/connect-dots'
      preLoaderRoute: typeof GamesConnectDotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/jigsaw': {
      id: '/games/jigsaw'
      path: '/games/jigsaw'
      fullPath: '/games/jigsaw'
      preLoaderRoute: typeof GamesJigsawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quiz': {
      id: '/games/quiz'
      path: '/games/quiz'
      fullPath: '/games/quiz'
      preLoaderRoute: typeof GamesQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/lobby': {
      id: '/join/lobby'
      path: '/lobby'
      fullPath: '/join/lobby'
      preLoaderRoute: typeof JoinLobbyRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/name': {
      id: '/join/name'
      path: '/name'
      fullPath: '/join/name'
      preLoaderRoute: typeof JoinNameRouteImport
      parentRoute: typeof JoinRoute
    }
    '/play/$roomId': {
      id: '/play/$roomId'
      path: '/play/$roomId'
      fullPath: '/play/$roomId'
      preLoaderRoute: typeof PlayRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareSlug': {
      id: '/share/$shareSlug'
      path: '/share/$shareSlug'
      fullPath: '/share/$shareSlug'
      preLoaderRoute: typeof ShareShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/room/$roomId': {
      id: '/author/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/author/room/$roomId'
      preLoaderRoute: typeof AuthorRoomRoomIdRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/sessions/$roomId': {
      id: '/author/sessions/$roomId'
      path: '/$roomId'
      fullPath: '/author/sessions/$roomId'
      preLoaderRoute: typeof AuthorSessionsRoomIdRouteImport
      parentRoute: typeof AuthorSessionsRoute
    }
  }
}

interface AuthorSessionsRouteChildren {
  AuthorSessionsRoomIdRoute: typeof AuthorSessionsRoomIdRoute
}

const AuthorSessionsRouteChildren: AuthorSessionsRouteChildren = {
  AuthorSessionsRoomIdRoute: AuthorSessionsRoomIdRoute,
}

const AuthorSessionsRouteWithChildren = AuthorSessionsRoute._addFileChildren(
  AuthorSessionsRouteChildren,
)

interface AuthorRouteChildren {
  AuthorAchievementsRoute: typeof AuthorAchievementsRoute
  AuthorCreateRoute: typeof AuthorCreateRoute
  AuthorLoginRoute: typeof AuthorLoginRoute
  AuthorParticipatedRoute: typeof AuthorParticipatedRoute
  AuthorQuestionsRoute: typeof AuthorQuestionsRoute
  AuthorRegisterRoute: typeof AuthorRegisterRoute
  AuthorSessionsRoute: typeof AuthorSessionsRouteWithChildren
  AuthorTemplatesRoute: typeof AuthorTemplatesRoute
  AuthorToolsRoute: typeof AuthorToolsRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  AuthorRoomRoomIdRoute: typeof AuthorRoomRoomIdRoute
}

const AuthorRouteChildren: AuthorRouteChildren = {
  AuthorAchievementsRoute: AuthorAchievementsRoute,
  AuthorCreateRoute: AuthorCreateRoute,
  AuthorLoginRoute: AuthorLoginRoute,
  AuthorParticipatedRoute: AuthorParticipatedRoute,
  AuthorQuestionsRoute: AuthorQuestionsRoute,
  AuthorRegisterRoute: AuthorRegisterRoute,
  AuthorSessionsRoute: AuthorSessionsRouteWithChildren,
  AuthorTemplatesRoute: AuthorTemplatesRoute,
  AuthorToolsRoute: AuthorToolsRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  AuthorRoomRoomIdRoute: AuthorRoomRoomIdRoute,
}

const AuthorRouteWithChildren =
  AuthorRoute._addFileChildren(AuthorRouteChildren)

interface JoinRouteChildren {
  JoinLobbyRoute: typeof JoinLobbyRoute
  JoinNameRoute: typeof JoinNameRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinLobbyRoute: JoinLobbyRoute,
  JoinNameRoute: JoinNameRoute,
  JoinIndexRoute: JoinIndexRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorRoute: AuthorRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  GamesConnectDotsRoute: GamesConnectDotsRoute,
  GamesJigsawRoute: GamesJigsawRoute,
  GamesQuizRoute: GamesQuizRoute,
  PlayRoomIdRoute: PlayRoomIdRoute,
  ShareShareSlugRoute: ShareShareSlugRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
